name: Lint, Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.17"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
            pyproject.toml

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install ruff pytest pytest-cov; fi

        - name: Condigure Headless
          run: |
            echo "SDL_VIDEODRIVER=dummy" >> $GITHUB_ENV
            echo "SDL_AUDIODRIVER=dummy"  >> $GITHUB_ENV

        - name: Lint 
          run: ruff check .

        - name: Test
          run: |
            pytest -q --maxfail=1 --disable-warnings -ra \
              --cov=kniffel --cov-report=xml:coverage.xml || exit 1

        - name: Upload coverage artifact
          uses: actions/upload-artifact@v4
          with:
            name: coverage-${{ matrix.os }}-py${{ matrix.python-version }}
            path: coverage.xml
        
